version: '3.9'

services:
  mysql:
    platform: linux/amd64
    image: postgres:14
    container_name: librora-postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: librora
