import { ModalProvider } from '@/components/Modal'
import './globals.css'
import '@picocss/pico'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { AlertProvider } from '@/components/Alert'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body className={inter.className}>
        <AlertProvider>
          <ModalProvider>
            <main>
              <div className="container">
                <div className="row">
                  <aside className="col-xs-2">
                    <nav>
                      <ul>
                        <li>Librora</li>
                        <hr />
                        <li>
                          <Link href="/users">Users</Link>
                        </li>
                      </ul>
                    </nav>
                  </aside>

                  <div className="col-xs-offset-1 col-xs-9">{children}</div>
                </div>
              </div>
            </main>
          </ModalProvider>
        </AlertProvider>
      </body>
    </html>
  )
}
