import { Country } from '@prisma/client'

/** @source https://gist.github.com/tadast/8827699 */

type CountryData = {
  country: string
  alphaCode2: Country
  alphaCode3: string
  numericCode: number
  lat: number
  lng: number
  emoji: string
}

export const countries: { [key in Country]: CountryData } = {
  AF: {
    country: 'Afghanistan',
    alphaCode2: 'AF',
    alphaCode3: 'AFG',
    numericCode: 4,
    lat: 33,
    lng: 65,
    emoji: '🇦🇫',
  },
  AL: {
    country: 'Albania',
    alphaCode2: 'AL',
    alphaCode3: 'ALB',
    numericCode: 8,
    lat: 41,
    lng: 20,
    emoji: '🇦🇱',
  },
  DZ: {
    country: 'Algeria',
    alphaCode2: 'DZ',
    alphaCode3: 'DZA',
    numericCode: 12,
    lat: 28,
    lng: 3,
    emoji: '🇩🇿',
  },
  AS: {
    country: 'American Samoa',
    alphaCode2: 'AS',
    alphaCode3: 'ASM',
    numericCode: 16,
    lat: -14.3333,
    lng: -170,
    emoji: '🇦🇸',
  },
  AD: {
    country: 'Andorra',
    alphaCode2: 'AD',
    alphaCode3: 'AND',
    numericCode: 20,
    lat: 42.5,
    lng: 1.6,
    emoji: '🇦🇩',
  },
  AO: {
    country: 'Angola',
    alphaCode2: 'AO',
    alphaCode3: 'AGO',
    numericCode: 24,
    lat: -12.5,
    lng: 18.5,
    emoji: '🇦🇴',
  },
  AI: {
    country: 'Anguilla',
    alphaCode2: 'AI',
    alphaCode3: 'AIA',
    numericCode: 660,
    lat: 18.25,
    lng: -63.1667,
    emoji: '🇦🇮',
  },
  AQ: {
    country: 'Antarctica',
    alphaCode2: 'AQ',
    alphaCode3: 'ATA',
    numericCode: 10,
    lat: -90,
    lng: 0,
    emoji: '🇦🇶',
  },
  AG: {
    country: 'Antigua and Barbuda',
    alphaCode2: 'AG',
    alphaCode3: 'ATG',
    numericCode: 28,
    lat: 17.05,
    lng: -61.8,
    emoji: '🇦🇬',
  },
  AR: {
    country: 'Argentina',
    alphaCode2: 'AR',
    alphaCode3: 'ARG',
    numericCode: 32,
    lat: -34,
    lng: -64,
    emoji: '🇦🇷',
  },
  AM: {
    country: 'Armenia',
    alphaCode2: 'AM',
    alphaCode3: 'ARM',
    numericCode: 51,
    lat: 40,
    lng: 45,
    emoji: '🇦🇲',
  },
  AW: {
    country: 'Aruba',
    alphaCode2: 'AW',
    alphaCode3: 'ABW',
    numericCode: 533,
    lat: 12.5,
    lng: -69.9667,
    emoji: '🇦🇼',
  },
  AU: {
    country: 'Australia',
    alphaCode2: 'AU',
    alphaCode3: 'AUS',
    numericCode: 36,
    lat: -27,
    lng: 133,
    emoji: '🇦🇺',
  },
  AT: {
    country: 'Austria',
    alphaCode2: 'AT',
    alphaCode3: 'AUT',
    numericCode: 40,
    lat: 47.3333,
    lng: 13.3333,
    emoji: '🇦🇹',
  },
  AZ: {
    country: 'Azerbaijan',
    alphaCode2: 'AZ',
    alphaCode3: 'AZE',
    numericCode: 31,
    lat: 40.5,
    lng: 47.5,
    emoji: '🇦🇿',
  },
  BS: {
    country: 'Bahamas',
    alphaCode2: 'BS',
    alphaCode3: 'BHS',
    numericCode: 44,
    lat: 24.25,
    lng: -76,
    emoji: '🇧🇸',
  },
  BH: {
    country: 'Bahrain',
    alphaCode2: 'BH',
    alphaCode3: 'BHR',
    numericCode: 48,
    lat: 26,
    lng: 50.55,
    emoji: '🇧🇭',
  },
  BD: {
    country: 'Bangladesh',
    alphaCode2: 'BD',
    alphaCode3: 'BGD',
    numericCode: 50,
    lat: 24,
    lng: 90,
    emoji: '🇧🇩',
  },
  BB: {
    country: 'Barbados',
    alphaCode2: 'BB',
    alphaCode3: 'BRB',
    numericCode: 52,
    lat: 13.1667,
    lng: -59.5333,
    emoji: '🇧🇧',
  },
  BY: {
    country: 'Belarus',
    alphaCode2: 'BY',
    alphaCode3: 'BLR',
    numericCode: 112,
    lat: 53,
    lng: 28,
    emoji: '🇧🇾',
  },
  BE: {
    country: 'Belgium',
    alphaCode2: 'BE',
    alphaCode3: 'BEL',
    numericCode: 56,
    lat: 50.8333,
    lng: 4,
    emoji: '🇧🇪',
  },
  BZ: {
    country: 'Belize',
    alphaCode2: 'BZ',
    alphaCode3: 'BLZ',
    numericCode: 84,
    lat: 17.25,
    lng: -88.75,
    emoji: '🇧🇿',
  },
  BJ: {
    country: 'Benin',
    alphaCode2: 'BJ',
    alphaCode3: 'BEN',
    numericCode: 204,
    lat: 9.5,
    lng: 2.25,
    emoji: '🇧🇯',
  },
  BM: {
    country: 'Bermuda',
    alphaCode2: 'BM',
    alphaCode3: 'BMU',
    numericCode: 60,
    lat: 32.3333,
    lng: -64.75,
    emoji: '🇧🇲',
  },
  BT: {
    country: 'Bhutan',
    alphaCode2: 'BT',
    alphaCode3: 'BTN',
    numericCode: 64,
    lat: 27.5,
    lng: 90.5,
    emoji: '🇧🇹',
  },
  BO: {
    country: 'Bolivia',
    alphaCode2: 'BO',
    alphaCode3: 'BOL',
    numericCode: 68,
    lat: -17,
    lng: -65,
    emoji: '🇧🇴',
  },
  BA: {
    country: 'Bosnia and Herzegovina',
    alphaCode2: 'BA',
    alphaCode3: 'BIH',
    numericCode: 70,
    lat: 44,
    lng: 18,
    emoji: '🇧🇦',
  },
  BW: {
    country: 'Botswana',
    alphaCode2: 'BW',
    alphaCode3: 'BWA',
    numericCode: 72,
    lat: -22,
    lng: 24,
    emoji: '🇧🇼',
  },
  BV: {
    country: 'Bouvet Island',
    alphaCode2: 'BV',
    alphaCode3: 'BVT',
    numericCode: 74,
    lat: -54.4333,
    lng: 3.4,
    emoji: '🇧🇻',
  },
  BR: {
    country: 'Brazil',
    alphaCode2: 'BR',
    alphaCode3: 'BRA',
    numericCode: 76,
    lat: -10,
    lng: -55,
    emoji: '🇧🇷',
  },
  IO: {
    country: 'British Indian Ocean Territory',
    alphaCode2: 'IO',
    alphaCode3: 'IOT',
    numericCode: 86,
    lat: -6,
    lng: 71.5,
    emoji: '🇮🇴',
  },
  BN: {
    country: 'Brunei',
    alphaCode2: 'BN',
    alphaCode3: 'BRN',
    numericCode: 96,
    lat: 4.5,
    lng: 114.6667,
    emoji: '🇧🇳',
  },
  BG: {
    country: 'Bulgaria',
    alphaCode2: 'BG',
    alphaCode3: 'BGR',
    numericCode: 100,
    lat: 43,
    lng: 25,
    emoji: '🇧🇬',
  },
  BF: {
    country: 'Burkina Faso',
    alphaCode2: 'BF',
    alphaCode3: 'BFA',
    numericCode: 854,
    lat: 13,
    lng: -2,
    emoji: '🇧🇫',
  },
  BI: {
    country: 'Burundi',
    alphaCode2: 'BI',
    alphaCode3: 'BDI',
    numericCode: 108,
    lat: -3.5,
    lng: 30,
    emoji: '🇧🇮',
  },
  KH: {
    country: 'Cambodia',
    alphaCode2: 'KH',
    alphaCode3: 'KHM',
    numericCode: 116,
    lat: 13,
    lng: 105,
    emoji: '🇰🇭',
  },
  CM: {
    country: 'Cameroon',
    alphaCode2: 'CM',
    alphaCode3: 'CMR',
    numericCode: 120,
    lat: 6,
    lng: 12,
    emoji: '🇨🇲',
  },
  CA: {
    country: 'Canada',
    alphaCode2: 'CA',
    alphaCode3: 'CAN',
    numericCode: 124,
    lat: 60,
    lng: -95,
    emoji: '🇨🇦',
  },
  CV: {
    country: 'Cape Verde',
    alphaCode2: 'CV',
    alphaCode3: 'CPV',
    numericCode: 132,
    lat: 16,
    lng: -24,
    emoji: '🇨🇻',
  },
  KY: {
    country: 'Cayman Islands',
    alphaCode2: 'KY',
    alphaCode3: 'CYM',
    numericCode: 136,
    lat: 19.5,
    lng: -80.5,
    emoji: '🇰🇾',
  },
  CF: {
    country: 'Central African Republic',
    alphaCode2: 'CF',
    alphaCode3: 'CAF',
    numericCode: 140,
    lat: 7,
    lng: 21,
    emoji: '🇨🇫',
  },
  TD: {
    country: 'Chad',
    alphaCode2: 'TD',
    alphaCode3: 'TCD',
    numericCode: 148,
    lat: 15,
    lng: 19,
    emoji: '🇹🇩',
  },
  CL: {
    country: 'Chile',
    alphaCode2: 'CL',
    alphaCode3: 'CHL',
    numericCode: 152,
    lat: -30,
    lng: -71,
    emoji: '🇨🇱',
  },
  CN: {
    country: 'China',
    alphaCode2: 'CN',
    alphaCode3: 'CHN',
    numericCode: 156,
    lat: 35,
    lng: 105,
    emoji: '🇨🇳',
  },
  CX: {
    country: 'Christmas Island',
    alphaCode2: 'CX',
    alphaCode3: 'CXR',
    numericCode: 162,
    lat: -10.5,
    lng: 105.6667,
    emoji: '🇨🇽',
  },
  CC: {
    country: 'Cocos (Keeling) Islands',
    alphaCode2: 'CC',
    alphaCode3: 'CCK',
    numericCode: 166,
    lat: -12.5,
    lng: 96.8333,
    emoji: '🇨🇨',
  },
  CO: {
    country: 'Colombia',
    alphaCode2: 'CO',
    alphaCode3: 'COL',
    numericCode: 170,
    lat: 4,
    lng: -72,
    emoji: '🇨🇴',
  },
  KM: {
    country: 'Comoros',
    alphaCode2: 'KM',
    alphaCode3: 'COM',
    numericCode: 174,
    lat: -12.1667,
    lng: 44.25,
    emoji: '🇰🇲',
  },
  CG: {
    country: 'Congo',
    alphaCode2: 'CG',
    alphaCode3: 'COG',
    numericCode: 178,
    lat: -1,
    lng: 15,
    emoji: '🇨🇬',
  },
  CD: {
    country: 'Congo',
    alphaCode2: 'CD',
    alphaCode3: 'COD',
    numericCode: 180,
    lat: 0,
    lng: 25,
    emoji: '🇨🇩',
  },
  CK: {
    country: 'Cook Islands',
    alphaCode2: 'CK',
    alphaCode3: 'COK',
    numericCode: 184,
    lat: -21.2333,
    lng: -159.7667,
    emoji: '🇨🇰',
  },
  CR: {
    country: 'Costa Rica',
    alphaCode2: 'CR',
    alphaCode3: 'CRI',
    numericCode: 188,
    lat: 10,
    lng: -84,
    emoji: '🇨🇷',
  },
  CI: {
    country: 'Ivory Coast',
    alphaCode2: 'CI',
    alphaCode3: 'CIV',
    numericCode: 384,
    lat: 8,
    lng: -5,
    emoji: '🇨🇮',
  },
  HR: {
    country: 'Croatia',
    alphaCode2: 'HR',
    alphaCode3: 'HRV',
    numericCode: 191,
    lat: 45.1667,
    lng: 15.5,
    emoji: '🇭🇷',
  },
  CU: {
    country: 'Cuba',
    alphaCode2: 'CU',
    alphaCode3: 'CUB',
    numericCode: 192,
    lat: 21.5,
    lng: -80,
    emoji: '🇨🇺',
  },
  CY: {
    country: 'Cyprus',
    alphaCode2: 'CY',
    alphaCode3: 'CYP',
    numericCode: 196,
    lat: 35,
    lng: 33,
    emoji: '🇨🇾',
  },
  CZ: {
    country: 'Czech Republic',
    alphaCode2: 'CZ',
    alphaCode3: 'CZE',
    numericCode: 203,
    lat: 49.75,
    lng: 15.5,
    emoji: '🇨🇿',
  },
  DK: {
    country: 'Denmark',
    alphaCode2: 'DK',
    alphaCode3: 'DNK',
    numericCode: 208,
    lat: 56,
    lng: 10,
    emoji: '🇩🇰',
  },
  DJ: {
    country: 'Djibouti',
    alphaCode2: 'DJ',
    alphaCode3: 'DJI',
    numericCode: 262,
    lat: 11.5,
    lng: 43,
    emoji: '🇩🇯',
  },
  DM: {
    country: 'Dominica',
    alphaCode2: 'DM',
    alphaCode3: 'DMA',
    numericCode: 212,
    lat: 15.4167,
    lng: -61.3333,
    emoji: '🇩🇲',
  },
  DO: {
    country: 'Dominican Republic',
    alphaCode2: 'DO',
    alphaCode3: 'DOM',
    numericCode: 214,
    lat: 19,
    lng: -70.6667,
    emoji: '🇩🇴',
  },
  EC: {
    country: 'Ecuador',
    alphaCode2: 'EC',
    alphaCode3: 'ECU',
    numericCode: 218,
    lat: -2,
    lng: -77.5,
    emoji: '🇪🇨',
  },
  EG: {
    country: 'Egypt',
    alphaCode2: 'EG',
    alphaCode3: 'EGY',
    numericCode: 818,
    lat: 27,
    lng: 30,
    emoji: '🇪🇬',
  },
  SV: {
    country: 'El Salvador',
    alphaCode2: 'SV',
    alphaCode3: 'SLV',
    numericCode: 222,
    lat: 13.8333,
    lng: -88.9167,
    emoji: '🇸🇻',
  },
  GQ: {
    country: 'Equatorial Guinea',
    alphaCode2: 'GQ',
    alphaCode3: 'GNQ',
    numericCode: 226,
    lat: 2,
    lng: 10,
    emoji: '🇬🇶',
  },
  ER: {
    country: 'Eritrea',
    alphaCode2: 'ER',
    alphaCode3: 'ERI',
    numericCode: 232,
    lat: 15,
    lng: 39,
    emoji: '🇪🇷',
  },
  EE: {
    country: 'Estonia',
    alphaCode2: 'EE',
    alphaCode3: 'EST',
    numericCode: 233,
    lat: 59,
    lng: 26,
    emoji: '🇪🇪',
  },
  ET: {
    country: 'Ethiopia',
    alphaCode2: 'ET',
    alphaCode3: 'ETH',
    numericCode: 231,
    lat: 8,
    lng: 38,
    emoji: '🇪🇹',
  },
  FK: {
    country: 'Falkland Islands (Malvinas)',
    alphaCode2: 'FK',
    alphaCode3: 'FLK',
    numericCode: 238,
    lat: -51.75,
    lng: -59,
    emoji: '🇫🇰',
  },
  FO: {
    country: 'Faroe Islands',
    alphaCode2: 'FO',
    alphaCode3: 'FRO',
    numericCode: 234,
    lat: 62,
    lng: -7,
    emoji: '🇫🇴',
  },
  FJ: {
    country: 'Fiji',
    alphaCode2: 'FJ',
    alphaCode3: 'FJI',
    numericCode: 242,
    lat: -18,
    lng: 175,
    emoji: '🇫🇯',
  },
  FI: {
    country: 'Finland',
    alphaCode2: 'FI',
    alphaCode3: 'FIN',
    numericCode: 246,
    lat: 64,
    lng: 26,
    emoji: '🇫🇮',
  },
  FR: {
    country: 'France',
    alphaCode2: 'FR',
    alphaCode3: 'FRA',
    numericCode: 250,
    lat: 46,
    lng: 2,
    emoji: '🇫🇷',
  },
  GF: {
    country: 'French Guiana',
    alphaCode2: 'GF',
    alphaCode3: 'GUF',
    numericCode: 254,
    lat: 4,
    lng: -53,
    emoji: '🇬🇫',
  },
  PF: {
    country: 'French Polynesia',
    alphaCode2: 'PF',
    alphaCode3: 'PYF',
    numericCode: 258,
    lat: -15,
    lng: -140,
    emoji: '🇵🇫',
  },
  TF: {
    country: 'French Southern Territories',
    alphaCode2: 'TF',
    alphaCode3: 'ATF',
    numericCode: 260,
    lat: -43,
    lng: 67,
    emoji: '🇹🇫',
  },
  GA: {
    country: 'Gabon',
    alphaCode2: 'GA',
    alphaCode3: 'GAB',
    numericCode: 266,
    lat: -1,
    lng: 11.75,
    emoji: '🇬🇦',
  },
  GM: {
    country: 'Gambia',
    alphaCode2: 'GM',
    alphaCode3: 'GMB',
    numericCode: 270,
    lat: 13.4667,
    lng: -16.5667,
    emoji: '🇬🇲',
  },
  GE: {
    country: 'Georgia',
    alphaCode2: 'GE',
    alphaCode3: 'GEO',
    numericCode: 268,
    lat: 42,
    lng: 43.5,
    emoji: '🇬🇪',
  },
  DE: {
    country: 'Germany',
    alphaCode2: 'DE',
    alphaCode3: 'DEU',
    numericCode: 276,
    lat: 51,
    lng: 9,
    emoji: '🇩🇪',
  },
  GH: {
    country: 'Ghana',
    alphaCode2: 'GH',
    alphaCode3: 'GHA',
    numericCode: 288,
    lat: 8,
    lng: -2,
    emoji: '🇬🇭',
  },
  GI: {
    country: 'Gibraltar',
    alphaCode2: 'GI',
    alphaCode3: 'GIB',
    numericCode: 292,
    lat: 36.1833,
    lng: -5.3667,
    emoji: '🇬🇮',
  },
  GR: {
    country: 'Greece',
    alphaCode2: 'GR',
    alphaCode3: 'GRC',
    numericCode: 300,
    lat: 39,
    lng: 22,
    emoji: '🇬🇷',
  },
  GL: {
    country: 'Greenland',
    alphaCode2: 'GL',
    alphaCode3: 'GRL',
    numericCode: 304,
    lat: 72,
    lng: -40,
    emoji: '🇬🇱',
  },
  GD: {
    country: 'Grenada',
    alphaCode2: 'GD',
    alphaCode3: 'GRD',
    numericCode: 308,
    lat: 12.1167,
    lng: -61.6667,
    emoji: '🇬🇩',
  },
  GP: {
    country: 'Guadeloupe',
    alphaCode2: 'GP',
    alphaCode3: 'GLP',
    numericCode: 312,
    lat: 16.25,
    lng: -61.5833,
    emoji: '🇬🇵',
  },
  GU: {
    country: 'Guam',
    alphaCode2: 'GU',
    alphaCode3: 'GUM',
    numericCode: 316,
    lat: 13.4667,
    lng: 144.7833,
    emoji: '🇬🇺',
  },
  GT: {
    country: 'Guatemala',
    alphaCode2: 'GT',
    alphaCode3: 'GTM',
    numericCode: 320,
    lat: 15.5,
    lng: -90.25,
    emoji: '🇬🇹',
  },
  GG: {
    country: 'Guernsey',
    alphaCode2: 'GG',
    alphaCode3: 'GGY',
    numericCode: 831,
    lat: 49.5,
    lng: -2.56,
    emoji: '🇬🇬',
  },
  GN: {
    country: 'Guinea',
    alphaCode2: 'GN',
    alphaCode3: 'GIN',
    numericCode: 324,
    lat: 11,
    lng: -10,
    emoji: '🇬🇳',
  },
  GW: {
    country: 'Guinea-Bissau',
    alphaCode2: 'GW',
    alphaCode3: 'GNB',
    numericCode: 624,
    lat: 12,
    lng: -15,
    emoji: '🇬🇼',
  },
  GY: {
    country: 'Guyana',
    alphaCode2: 'GY',
    alphaCode3: 'GUY',
    numericCode: 328,
    lat: 5,
    lng: -59,
    emoji: '🇬🇾',
  },
  HT: {
    country: 'Haiti',
    alphaCode2: 'HT',
    alphaCode3: 'HTI',
    numericCode: 332,
    lat: 19,
    lng: -72.4167,
    emoji: '🇭🇹',
  },
  HM: {
    country: 'Heard Island and McDonald Islands',
    alphaCode2: 'HM',
    alphaCode3: 'HMD',
    numericCode: 334,
    lat: -53.1,
    lng: 72.5167,
    emoji: '🇭🇲',
  },
  VA: {
    country: 'Holy See (Vatican City State)',
    alphaCode2: 'VA',
    alphaCode3: 'VAT',
    numericCode: 336,
    lat: 41.9,
    lng: 12.45,
    emoji: '🇻🇦',
  },
  HN: {
    country: 'Honduras',
    alphaCode2: 'HN',
    alphaCode3: 'HND',
    numericCode: 340,
    lat: 15,
    lng: -86.5,
    emoji: '🇭🇳',
  },
  HK: {
    country: 'Hong Kong',
    alphaCode2: 'HK',
    alphaCode3: 'HKG',
    numericCode: 344,
    lat: 22.25,
    lng: 114.1667,
    emoji: '🇭🇰',
  },
  HU: {
    country: 'Hungary',
    alphaCode2: 'HU',
    alphaCode3: 'HUN',
    numericCode: 348,
    lat: 47,
    lng: 20,
    emoji: '🇭🇺',
  },
  IS: {
    country: 'Iceland',
    alphaCode2: 'IS',
    alphaCode3: 'ISL',
    numericCode: 352,
    lat: 65,
    lng: -18,
    emoji: '🇮🇸',
  },
  IN: {
    country: 'India',
    alphaCode2: 'IN',
    alphaCode3: 'IND',
    numericCode: 356,
    lat: 20,
    lng: 77,
    emoji: '🇮🇳',
  },
  ID: {
    country: 'Indonesia',
    alphaCode2: 'ID',
    alphaCode3: 'IDN',
    numericCode: 360,
    lat: -5,
    lng: 120,
    emoji: '🇮🇩',
  },
  IR: {
    country: 'Iran',
    alphaCode2: 'IR',
    alphaCode3: 'IRN',
    numericCode: 364,
    lat: 32,
    lng: 53,
    emoji: '🇮🇷',
  },
  IQ: {
    country: 'Iraq',
    alphaCode2: 'IQ',
    alphaCode3: 'IRQ',
    numericCode: 368,
    lat: 33,
    lng: 44,
    emoji: '🇮🇶',
  },
  IE: {
    country: 'Ireland',
    alphaCode2: 'IE',
    alphaCode3: 'IRL',
    numericCode: 372,
    lat: 53,
    lng: -8,
    emoji: '🇮🇪',
  },
  IM: {
    country: 'Isle of Man',
    alphaCode2: 'IM',
    alphaCode3: 'IMN',
    numericCode: 833,
    lat: 54.23,
    lng: -4.55,
    emoji: '🇮🇲',
  },
  IL: {
    country: 'Israel',
    alphaCode2: 'IL',
    alphaCode3: 'ISR',
    numericCode: 376,
    lat: 31.5,
    lng: 34.75,
    emoji: '🇮🇱',
  },
  IT: {
    country: 'Italy',
    alphaCode2: 'IT',
    alphaCode3: 'ITA',
    numericCode: 380,
    lat: 42.8333,
    lng: 12.8333,
    emoji: '🇮🇹',
  },
  JM: {
    country: 'Jamaica',
    alphaCode2: 'JM',
    alphaCode3: 'JAM',
    numericCode: 388,
    lat: 18.25,
    lng: -77.5,
    emoji: '🇯🇲',
  },
  JP: {
    country: 'Japan',
    alphaCode2: 'JP',
    alphaCode3: 'JPN',
    numericCode: 392,
    lat: 36,
    lng: 138,
    emoji: '🇯🇵',
  },
  JE: {
    country: 'Jersey',
    alphaCode2: 'JE',
    alphaCode3: 'JEY',
    numericCode: 832,
    lat: 49.21,
    lng: -2.13,
    emoji: '🇯🇪',
  },
  JO: {
    country: 'Jordan',
    alphaCode2: 'JO',
    alphaCode3: 'JOR',
    numericCode: 400,
    lat: 31,
    lng: 36,
    emoji: '🇯🇴',
  },
  KZ: {
    country: 'Kazakhstan',
    alphaCode2: 'KZ',
    alphaCode3: 'KAZ',
    numericCode: 398,
    lat: 48,
    lng: 68,
    emoji: '🇰🇿',
  },
  KE: {
    country: 'Kenya',
    alphaCode2: 'KE',
    alphaCode3: 'KEN',
    numericCode: 404,
    lat: 1,
    lng: 38,
    emoji: '🇰🇪',
  },
  KI: {
    country: 'Kiribati',
    alphaCode2: 'KI',
    alphaCode3: 'KIR',
    numericCode: 296,
    lat: 1.4167,
    lng: 173,
    emoji: '🇰🇮',
  },
  KP: {
    country: 'Korea',
    alphaCode2: 'KP',
    alphaCode3: 'PRK',
    numericCode: 408,
    lat: 40,
    lng: 127,
    emoji: '🇰🇵',
  },
  KR: {
    country: 'South Korea',
    alphaCode2: 'KR',
    alphaCode3: 'KOR',
    numericCode: 410,
    lat: 37,
    lng: 127.5,
    emoji: '🇰🇷',
  },
  KW: {
    country: 'Kuwait',
    alphaCode2: 'KW',
    alphaCode3: 'KWT',
    numericCode: 414,
    lat: 29.3375,
    lng: 47.6581,
    emoji: '🇰🇼',
  },
  KG: {
    country: 'Kyrgyzstan',
    alphaCode2: 'KG',
    alphaCode3: 'KGZ',
    numericCode: 417,
    lat: 41,
    lng: 75,
    emoji: '🇰🇬',
  },
  LA: {
    country: "Lao People's Democratic Republic",
    alphaCode2: 'LA',
    alphaCode3: 'LAO',
    numericCode: 418,
    lat: 18,
    lng: 105,
    emoji: '🇱🇦',
  },
  LV: {
    country: 'Latvia',
    alphaCode2: 'LV',
    alphaCode3: 'LVA',
    numericCode: 428,
    lat: 57,
    lng: 25,
    emoji: '🇱🇻',
  },
  LB: {
    country: 'Lebanon',
    alphaCode2: 'LB',
    alphaCode3: 'LBN',
    numericCode: 422,
    lat: 33.8333,
    lng: 35.8333,
    emoji: '🇱🇧',
  },
  LS: {
    country: 'Lesotho',
    alphaCode2: 'LS',
    alphaCode3: 'LSO',
    numericCode: 426,
    lat: -29.5,
    lng: 28.5,
    emoji: '🇱🇸',
  },
  LR: {
    country: 'Liberia',
    alphaCode2: 'LR',
    alphaCode3: 'LBR',
    numericCode: 430,
    lat: 6.5,
    lng: -9.5,
    emoji: '🇱🇷',
  },
  LY: {
    country: 'Libya',
    alphaCode2: 'LY',
    alphaCode3: 'LBY',
    numericCode: 434,
    lat: 25,
    lng: 17,
    emoji: '🇱🇾',
  },
  LI: {
    country: 'Liechtenstein',
    alphaCode2: 'LI',
    alphaCode3: 'LIE',
    numericCode: 438,
    lat: 47.1667,
    lng: 9.5333,
    emoji: '🇱🇮',
  },
  LT: {
    country: 'Lithuania',
    alphaCode2: 'LT',
    alphaCode3: 'LTU',
    numericCode: 440,
    lat: 56,
    lng: 24,
    emoji: '🇱🇹',
  },
  LU: {
    country: 'Luxembourg',
    alphaCode2: 'LU',
    alphaCode3: 'LUX',
    numericCode: 442,
    lat: 49.75,
    lng: 6.1667,
    emoji: '🇱🇺',
  },
  MO: {
    country: 'Macao',
    alphaCode2: 'MO',
    alphaCode3: 'MAC',
    numericCode: 446,
    lat: 22.1667,
    lng: 113.55,
    emoji: '🇲🇴',
  },
  MK: {
    country: 'Macedonia',
    alphaCode2: 'MK',
    alphaCode3: 'MKD',
    numericCode: 807,
    lat: 41.8333,
    lng: 22,
    emoji: '🇲🇰',
  },
  MG: {
    country: 'Madagascar',
    alphaCode2: 'MG',
    alphaCode3: 'MDG',
    numericCode: 450,
    lat: -20,
    lng: 47,
    emoji: '🇲🇬',
  },
  MW: {
    country: 'Malawi',
    alphaCode2: 'MW',
    alphaCode3: 'MWI',
    numericCode: 454,
    lat: -13.5,
    lng: 34,
    emoji: '🇲🇼',
  },
  MY: {
    country: 'Malaysia',
    alphaCode2: 'MY',
    alphaCode3: 'MYS',
    numericCode: 458,
    lat: 2.5,
    lng: 112.5,
    emoji: '🇲🇾',
  },
  MV: {
    country: 'Maldives',
    alphaCode2: 'MV',
    alphaCode3: 'MDV',
    numericCode: 462,
    lat: 3.25,
    lng: 73,
    emoji: '🇲🇻',
  },
  ML: {
    country: 'Mali',
    alphaCode2: 'ML',
    alphaCode3: 'MLI',
    numericCode: 466,
    lat: 17,
    lng: -4,
    emoji: '🇲🇱',
  },
  MT: {
    country: 'Malta',
    alphaCode2: 'MT',
    alphaCode3: 'MLT',
    numericCode: 470,
    lat: 35.8333,
    lng: 14.5833,
    emoji: '🇲🇹',
  },
  MH: {
    country: 'Marshall Islands',
    alphaCode2: 'MH',
    alphaCode3: 'MHL',
    numericCode: 584,
    lat: 9,
    lng: 168,
    emoji: '🇲🇭',
  },
  MQ: {
    country: 'Martinique',
    alphaCode2: 'MQ',
    alphaCode3: 'MTQ',
    numericCode: 474,
    lat: 14.6667,
    lng: -61,
    emoji: '🇲🇶',
  },
  MR: {
    country: 'Mauritania',
    alphaCode2: 'MR',
    alphaCode3: 'MRT',
    numericCode: 478,
    lat: 20,
    lng: -12,
    emoji: '🇲🇷',
  },
  MU: {
    country: 'Mauritius',
    alphaCode2: 'MU',
    alphaCode3: 'MUS',
    numericCode: 480,
    lat: -20.2833,
    lng: 57.55,
    emoji: '🇲🇺',
  },
  YT: {
    country: 'Mayotte',
    alphaCode2: 'YT',
    alphaCode3: 'MYT',
    numericCode: 175,
    lat: -12.8333,
    lng: 45.1667,
    emoji: '🇾🇹',
  },
  MX: {
    country: 'Mexico',
    alphaCode2: 'MX',
    alphaCode3: 'MEX',
    numericCode: 484,
    lat: 23,
    lng: -102,
    emoji: '🇲🇽',
  },
  FM: {
    country: 'Micronesia',
    alphaCode2: 'FM',
    alphaCode3: 'FSM',
    numericCode: 583,
    lat: 6.9167,
    lng: 158.25,
    emoji: '🇫🇲',
  },
  MD: {
    country: 'Moldova',
    alphaCode2: 'MD',
    alphaCode3: 'MDA',
    numericCode: 498,
    lat: 47,
    lng: 29,
    emoji: '🇲🇩',
  },
  MC: {
    country: 'Monaco',
    alphaCode2: 'MC',
    alphaCode3: 'MCO',
    numericCode: 492,
    lat: 43.7333,
    lng: 7.4,
    emoji: '🇲🇨',
  },
  MN: {
    country: 'Mongolia',
    alphaCode2: 'MN',
    alphaCode3: 'MNG',
    numericCode: 496,
    lat: 46,
    lng: 105,
    emoji: '🇲🇳',
  },
  ME: {
    country: 'Montenegro',
    alphaCode2: 'ME',
    alphaCode3: 'MNE',
    numericCode: 499,
    lat: 42,
    lng: 19,
    emoji: '🇲🇪',
  },
  MS: {
    country: 'Montserrat',
    alphaCode2: 'MS',
    alphaCode3: 'MSR',
    numericCode: 500,
    lat: 16.75,
    lng: -62.2,
    emoji: '🇲🇸',
  },
  MA: {
    country: 'Morocco',
    alphaCode2: 'MA',
    alphaCode3: 'MAR',
    numericCode: 504,
    lat: 32,
    lng: -5,
    emoji: '🇲🇦',
  },
  MZ: {
    country: 'Mozambique',
    alphaCode2: 'MZ',
    alphaCode3: 'MOZ',
    numericCode: 508,
    lat: -18.25,
    lng: 35,
    emoji: '🇲🇿',
  },
  MM: {
    country: 'Myanmar',
    alphaCode2: 'MM',
    alphaCode3: 'MMR',
    numericCode: 104,
    lat: 22,
    lng: 98,
    emoji: '🇲🇲',
  },
  NA: {
    country: 'Namibia',
    alphaCode2: 'NA',
    alphaCode3: 'NAM',
    numericCode: 516,
    lat: -22,
    lng: 17,
    emoji: '🇳🇦',
  },
  NR: {
    country: 'Nauru',
    alphaCode2: 'NR',
    alphaCode3: 'NRU',
    numericCode: 520,
    lat: -0.5333,
    lng: 166.9167,
    emoji: '🇳🇷',
  },
  NP: {
    country: 'Nepal',
    alphaCode2: 'NP',
    alphaCode3: 'NPL',
    numericCode: 524,
    lat: 28,
    lng: 84,
    emoji: '🇳🇵',
  },
  NL: {
    country: 'Netherlands',
    alphaCode2: 'NL',
    alphaCode3: 'NLD',
    numericCode: 528,
    lat: 52.5,
    lng: 5.75,
    emoji: '🇳🇱',
  },
  AN: {
    country: 'Netherlands Antilles',
    alphaCode2: 'AN',
    alphaCode3: 'ANT',
    numericCode: 530,
    lat: 12.25,
    lng: -68.75,
    emoji: '🇦🇳',
  },
  NC: {
    country: 'New Caledonia',
    alphaCode2: 'NC',
    alphaCode3: 'NCL',
    numericCode: 540,
    lat: -21.5,
    lng: 165.5,
    emoji: '🇳🇨',
  },
  NZ: {
    country: 'New Zealand',
    alphaCode2: 'NZ',
    alphaCode3: 'NZL',
    numericCode: 554,
    lat: -41,
    lng: 174,
    emoji: '🇳🇿',
  },
  NI: {
    country: 'Nicaragua',
    alphaCode2: 'NI',
    alphaCode3: 'NIC',
    numericCode: 558,
    lat: 13,
    lng: -85,
    emoji: '🇳🇮',
  },
  NE: {
    country: 'Niger',
    alphaCode2: 'NE',
    alphaCode3: 'NER',
    numericCode: 562,
    lat: 16,
    lng: 8,
    emoji: '🇳🇪',
  },
  NG: {
    country: 'Nigeria',
    alphaCode2: 'NG',
    alphaCode3: 'NGA',
    numericCode: 566,
    lat: 10,
    lng: 8,
    emoji: '🇳🇬',
  },
  NU: {
    country: 'Niue',
    alphaCode2: 'NU',
    alphaCode3: 'NIU',
    numericCode: 570,
    lat: -19.0333,
    lng: -169.8667,
    emoji: '🇳🇺',
  },
  NF: {
    country: 'Norfolk Island',
    alphaCode2: 'NF',
    alphaCode3: 'NFK',
    numericCode: 574,
    lat: -29.0333,
    lng: 167.95,
    emoji: '🇳🇫',
  },
  MP: {
    country: 'Northern Mariana Islands',
    alphaCode2: 'MP',
    alphaCode3: 'MNP',
    numericCode: 580,
    lat: 15.2,
    lng: 145.75,
    emoji: '🇲🇵',
  },
  NO: {
    country: 'Norway',
    alphaCode2: 'NO',
    alphaCode3: 'NOR',
    numericCode: 578,
    lat: 62,
    lng: 10,
    emoji: '🇳🇴',
  },
  OM: {
    country: 'Oman',
    alphaCode2: 'OM',
    alphaCode3: 'OMN',
    numericCode: 512,
    lat: 21,
    lng: 57,
    emoji: '🇴🇲',
  },
  PK: {
    country: 'Pakistan',
    alphaCode2: 'PK',
    alphaCode3: 'PAK',
    numericCode: 586,
    lat: 30,
    lng: 70,
    emoji: '🇵🇰',
  },
  PW: {
    country: 'Palau',
    alphaCode2: 'PW',
    alphaCode3: 'PLW',
    numericCode: 585,
    lat: 7.5,
    lng: 134.5,
    emoji: '🇵🇼',
  },
  PS: {
    country: 'Palestinian Territory',
    alphaCode2: 'PS',
    alphaCode3: 'PSE',
    numericCode: 275,
    lat: 32,
    lng: 35.25,
    emoji: '🇵🇸',
  },
  PA: {
    country: 'Panama',
    alphaCode2: 'PA',
    alphaCode3: 'PAN',
    numericCode: 591,
    lat: 9,
    lng: -80,
    emoji: '🇵🇦',
  },
  PG: {
    country: 'Papua New Guinea',
    alphaCode2: 'PG',
    alphaCode3: 'PNG',
    numericCode: 598,
    lat: -6,
    lng: 147,
    emoji: '🇵🇬',
  },
  PY: {
    country: 'Paraguay',
    alphaCode2: 'PY',
    alphaCode3: 'PRY',
    numericCode: 600,
    lat: -23,
    lng: -58,
    emoji: '🇵🇾',
  },
  PE: {
    country: 'Peru',
    alphaCode2: 'PE',
    alphaCode3: 'PER',
    numericCode: 604,
    lat: -10,
    lng: -76,
    emoji: '🇵🇪',
  },
  PH: {
    country: 'Philippines',
    alphaCode2: 'PH',
    alphaCode3: 'PHL',
    numericCode: 608,
    lat: 13,
    lng: 122,
    emoji: '🇵🇭',
  },
  PN: {
    country: 'Pitcairn',
    alphaCode2: 'PN',
    alphaCode3: 'PCN',
    numericCode: 612,
    lat: -24.7,
    lng: -127.4,
    emoji: '🇵🇳',
  },
  PL: {
    country: 'Poland',
    alphaCode2: 'PL',
    alphaCode3: 'POL',
    numericCode: 616,
    lat: 52,
    lng: 20,
    emoji: '🇵🇱',
  },
  PT: {
    country: 'Portugal',
    alphaCode2: 'PT',
    alphaCode3: 'PRT',
    numericCode: 620,
    lat: 39.5,
    lng: -8,
    emoji: '🇵🇹',
  },
  PR: {
    country: 'Puerto Rico',
    alphaCode2: 'PR',
    alphaCode3: 'PRI',
    numericCode: 630,
    lat: 18.25,
    lng: -66.5,
    emoji: '🇵🇷',
  },
  QA: {
    country: 'Qatar',
    alphaCode2: 'QA',
    alphaCode3: 'QAT',
    numericCode: 634,
    lat: 25.5,
    lng: 51.25,
    emoji: '🇶🇦',
  },
  RE: {
    country: 'Réunion',
    alphaCode2: 'RE',
    alphaCode3: 'REU',
    numericCode: 638,
    lat: -21.1,
    lng: 55.6,
    emoji: '🇷🇪',
  },
  RO: {
    country: 'Romania',
    alphaCode2: 'RO',
    alphaCode3: 'ROU',
    numericCode: 642,
    lat: 46,
    lng: 25,
    emoji: '🇷🇴',
  },
  RU: {
    country: 'Russia',
    alphaCode2: 'RU',
    alphaCode3: 'RUS',
    numericCode: 643,
    lat: 60,
    lng: 100,
    emoji: '🇷🇺',
  },
  RW: {
    country: 'Rwanda',
    alphaCode2: 'RW',
    alphaCode3: 'RWA',
    numericCode: 646,
    lat: -2,
    lng: 30,
    emoji: '🇷🇼',
  },
  SH: {
    country: 'Saint Helena',
    alphaCode2: 'SH',
    alphaCode3: 'SHN',
    numericCode: 654,
    lat: -15.9333,
    lng: -5.7,
    emoji: '🇸🇭',
  },
  KN: {
    country: 'Saint Kitts and Nevis',
    alphaCode2: 'KN',
    alphaCode3: 'KNA',
    numericCode: 659,
    lat: 17.3333,
    lng: -62.75,
    emoji: '🇰🇳',
  },
  LC: {
    country: 'Saint Lucia',
    alphaCode2: 'LC',
    alphaCode3: 'LCA',
    numericCode: 662,
    lat: 13.8833,
    lng: -61.1333,
    emoji: '🇱🇨',
  },
  PM: {
    country: 'Saint Pierre and Miquelon',
    alphaCode2: 'PM',
    alphaCode3: 'SPM',
    numericCode: 666,
    lat: 46.8333,
    lng: -56.3333,
    emoji: '🇵🇲',
  },
  VC: {
    country: 'Saint Vincent and the Grenadines',
    alphaCode2: 'VC',
    alphaCode3: 'VCT',
    numericCode: 670,
    lat: 13.25,
    lng: -61.2,
    emoji: '🇻🇨',
  },
  WS: {
    country: 'Samoa',
    alphaCode2: 'WS',
    alphaCode3: 'WSM',
    numericCode: 882,
    lat: -13.5833,
    lng: -172.3333,
    emoji: '🇼🇸',
  },
  SM: {
    country: 'San Marino',
    alphaCode2: 'SM',
    alphaCode3: 'SMR',
    numericCode: 674,
    lat: 43.7667,
    lng: 12.4167,
    emoji: '🇸🇲',
  },
  ST: {
    country: 'Sao Tome and Principe',
    alphaCode2: 'ST',
    alphaCode3: 'STP',
    numericCode: 678,
    lat: 1,
    lng: 7,
    emoji: '🇸🇹',
  },
  SA: {
    country: 'Saudi Arabia',
    alphaCode2: 'SA',
    alphaCode3: 'SAU',
    numericCode: 682,
    lat: 25,
    lng: 45,
    emoji: '🇸🇦',
  },
  SN: {
    country: 'Senegal',
    alphaCode2: 'SN',
    alphaCode3: 'SEN',
    numericCode: 686,
    lat: 14,
    lng: -14,
    emoji: '🇸🇳',
  },
  RS: {
    country: 'Serbia',
    alphaCode2: 'RS',
    alphaCode3: 'SRB',
    numericCode: 688,
    lat: 44,
    lng: 21,
    emoji: '🇷🇸',
  },
  SC: {
    country: 'Seychelles',
    alphaCode2: 'SC',
    alphaCode3: 'SYC',
    numericCode: 690,
    lat: -4.5833,
    lng: 55.6667,
    emoji: '🇸🇨',
  },
  SL: {
    country: 'Sierra Leone',
    alphaCode2: 'SL',
    alphaCode3: 'SLE',
    numericCode: 694,
    lat: 8.5,
    lng: -11.5,
    emoji: '🇸🇱',
  },
  SG: {
    country: 'Singapore',
    alphaCode2: 'SG',
    alphaCode3: 'SGP',
    numericCode: 702,
    lat: 1.3667,
    lng: 103.8,
    emoji: '🇸🇬',
  },
  SK: {
    country: 'Slovakia',
    alphaCode2: 'SK',
    alphaCode3: 'SVK',
    numericCode: 703,
    lat: 48.6667,
    lng: 19.5,
    emoji: '🇸🇰',
  },
  SI: {
    country: 'Slovenia',
    alphaCode2: 'SI',
    alphaCode3: 'SVN',
    numericCode: 705,
    lat: 46,
    lng: 15,
    emoji: '🇸🇮',
  },
  SB: {
    country: 'Solomon Islands',
    alphaCode2: 'SB',
    alphaCode3: 'SLB',
    numericCode: 90,
    lat: -8,
    lng: 159,
    emoji: '🇸🇧',
  },
  SO: {
    country: 'Somalia',
    alphaCode2: 'SO',
    alphaCode3: 'SOM',
    numericCode: 706,
    lat: 10,
    lng: 49,
    emoji: '🇸🇴',
  },
  ZA: {
    country: 'South Africa',
    alphaCode2: 'ZA',
    alphaCode3: 'ZAF',
    numericCode: 710,
    lat: -29,
    lng: 24,
    emoji: '🇿🇦',
  },
  GS: {
    country: 'South Georgia',
    alphaCode2: 'GS',
    alphaCode3: 'SGS',
    numericCode: 239,
    lat: -54.5,
    lng: -37,
    emoji: '🇬🇸',
  },
  SS: {
    country: 'South Sudan',
    alphaCode2: 'SS',
    alphaCode3: 'SSD',
    numericCode: 728,
    lat: 8,
    lng: 30,
    emoji: '🇸🇸',
  },
  ES: {
    country: 'Spain',
    alphaCode2: 'ES',
    alphaCode3: 'ESP',
    numericCode: 724,
    lat: 40,
    lng: -4,
    emoji: '🇪🇸',
  },
  LK: {
    country: 'Sri Lanka',
    alphaCode2: 'LK',
    alphaCode3: 'LKA',
    numericCode: 144,
    lat: 7,
    lng: 81,
    emoji: '🇱🇰',
  },
  SD: {
    country: 'Sudan',
    alphaCode2: 'SD',
    alphaCode3: 'SDN',
    numericCode: 736,
    lat: 15,
    lng: 30,
    emoji: '🇸🇩',
  },
  SR: {
    country: 'Suriname',
    alphaCode2: 'SR',
    alphaCode3: 'SUR',
    numericCode: 740,
    lat: 4,
    lng: -56,
    emoji: '🇸🇷',
  },
  SJ: {
    country: 'Svalbard and Jan Mayen',
    alphaCode2: 'SJ',
    alphaCode3: 'SJM',
    numericCode: 744,
    lat: 78,
    lng: 20,
    emoji: '🇸🇯',
  },
  SZ: {
    country: 'Swaziland',
    alphaCode2: 'SZ',
    alphaCode3: 'SWZ',
    numericCode: 748,
    lat: -26.5,
    lng: 31.5,
    emoji: '🇸🇿',
  },
  SE: {
    country: 'Sweden',
    alphaCode2: 'SE',
    alphaCode3: 'SWE',
    numericCode: 752,
    lat: 62,
    lng: 15,
    emoji: '🇸🇪',
  },
  CH: {
    country: 'Switzerland',
    alphaCode2: 'CH',
    alphaCode3: 'CHE',
    numericCode: 756,
    lat: 47,
    lng: 8,
    emoji: '🇨🇭',
  },
  SY: {
    country: 'Syrian Arab Republic',
    alphaCode2: 'SY',
    alphaCode3: 'SYR',
    numericCode: 760,
    lat: 35,
    lng: 38,
    emoji: '🇸🇾',
  },
  TW: {
    country: 'Taiwan',
    alphaCode2: 'TW',
    alphaCode3: 'TWN',
    numericCode: 158,
    lat: 23.5,
    lng: 121,
    emoji: '🇹🇼',
  },
  TJ: {
    country: 'Tajikistan',
    alphaCode2: 'TJ',
    alphaCode3: 'TJK',
    numericCode: 762,
    lat: 39,
    lng: 71,
    emoji: '🇹🇯',
  },
  TZ: {
    country: 'Tanzania',
    alphaCode2: 'TZ',
    alphaCode3: 'TZA',
    numericCode: 834,
    lat: -6,
    lng: 35,
    emoji: '🇹🇿',
  },
  TH: {
    country: 'Thailand',
    alphaCode2: 'TH',
    alphaCode3: 'THA',
    numericCode: 764,
    lat: 15,
    lng: 100,
    emoji: '🇹🇭',
  },
  TL: {
    country: 'Timor-Leste',
    alphaCode2: 'TL',
    alphaCode3: 'TLS',
    numericCode: 626,
    lat: -8.55,
    lng: 125.5167,
    emoji: '🇹🇱',
  },
  TG: {
    country: 'Togo',
    alphaCode2: 'TG',
    alphaCode3: 'TGO',
    numericCode: 768,
    lat: 8,
    lng: 1.1667,
    emoji: '🇹🇬',
  },
  TK: {
    country: 'Tokelau',
    alphaCode2: 'TK',
    alphaCode3: 'TKL',
    numericCode: 772,
    lat: -9,
    lng: -172,
    emoji: '🇹🇰',
  },
  TO: {
    country: 'Tonga',
    alphaCode2: 'TO',
    alphaCode3: 'TON',
    numericCode: 776,
    lat: -20,
    lng: -175,
    emoji: '🇹🇴',
  },
  TT: {
    country: 'Trinidad and Tobago',
    alphaCode2: 'TT',
    alphaCode3: 'TTO',
    numericCode: 780,
    lat: 11,
    lng: -61,
    emoji: '🇹🇹',
  },
  TN: {
    country: 'Tunisia',
    alphaCode2: 'TN',
    alphaCode3: 'TUN',
    numericCode: 788,
    lat: 34,
    lng: 9,
    emoji: '🇹🇳',
  },
  TR: {
    country: 'Turkey',
    alphaCode2: 'TR',
    alphaCode3: 'TUR',
    numericCode: 792,
    lat: 39,
    lng: 35,
    emoji: '🇹🇷',
  },
  TM: {
    country: 'Turkmenistan',
    alphaCode2: 'TM',
    alphaCode3: 'TKM',
    numericCode: 795,
    lat: 40,
    lng: 60,
    emoji: '🇹🇲',
  },
  TC: {
    country: 'Turks and Caicos Islands',
    alphaCode2: 'TC',
    alphaCode3: 'TCA',
    numericCode: 796,
    lat: 21.75,
    lng: -71.5833,
    emoji: '🇹🇨',
  },
  TV: {
    country: 'Tuvalu',
    alphaCode2: 'TV',
    alphaCode3: 'TUV',
    numericCode: 798,
    lat: -8,
    lng: 178,
    emoji: '🇹🇻',
  },
  UG: {
    country: 'Uganda',
    alphaCode2: 'UG',
    alphaCode3: 'UGA',
    numericCode: 800,
    lat: 1,
    lng: 32,
    emoji: '🇺🇬',
  },
  UA: {
    country: 'Ukraine',
    alphaCode2: 'UA',
    alphaCode3: 'UKR',
    numericCode: 804,
    lat: 49,
    lng: 32,
    emoji: '🇺🇦',
  },
  AE: {
    country: 'United Arab Emirates',
    alphaCode2: 'AE',
    alphaCode3: 'ARE',
    numericCode: 784,
    lat: 24,
    lng: 54,
    emoji: '🇦🇪',
  },
  GB: {
    country: 'United Kingdom',
    alphaCode2: 'GB',
    alphaCode3: 'GBR',
    numericCode: 826,
    lat: 54,
    lng: -2,
    emoji: '🇬🇧',
  },
  US: {
    country: 'United States',
    alphaCode2: 'US',
    alphaCode3: 'USA',
    numericCode: 840,
    lat: 38,
    lng: -97,
    emoji: '🇺🇸',
  },
  UM: {
    country: 'United States MOI',
    alphaCode2: 'UM',
    alphaCode3: 'UMI',
    numericCode: 581,
    lat: 19.2833,
    lng: 166.6,
    emoji: '🇺🇲',
  },
  UY: {
    country: 'Uruguay',
    alphaCode2: 'UY',
    alphaCode3: 'URY',
    numericCode: 858,
    lat: -33,
    lng: -56,
    emoji: '🇺🇾',
  },
  UZ: {
    country: 'Uzbekistan',
    alphaCode2: 'UZ',
    alphaCode3: 'UZB',
    numericCode: 860,
    lat: 41,
    lng: 64,
    emoji: '🇺🇿',
  },
  VU: {
    country: 'Vanuatu',
    alphaCode2: 'VU',
    alphaCode3: 'VUT',
    numericCode: 548,
    lat: -16,
    lng: 167,
    emoji: '🇻🇺',
  },
  VE: {
    country: 'Venezuela',
    alphaCode2: 'VE',
    alphaCode3: 'VEN',
    numericCode: 862,
    lat: 8,
    lng: -66,
    emoji: '🇻🇪',
  },
  VN: {
    country: 'Vietnam',
    alphaCode2: 'VN',
    alphaCode3: 'VNM',
    numericCode: 704,
    lat: 16,
    lng: 106,
    emoji: '🇻🇳',
  },
  VG: {
    country: 'Virgin Islands, British',
    alphaCode2: 'VG',
    alphaCode3: 'VGB',
    numericCode: 92,
    lat: 18.5,
    lng: -64.5,
    emoji: '🇻🇬',
  },
  VI: {
    country: 'Virgin Islands, U.S.',
    alphaCode2: 'VI',
    alphaCode3: 'VIR',
    numericCode: 850,
    lat: 18.3333,
    lng: -64.8333,
    emoji: '🇻🇮',
  },
  WF: {
    country: 'Wallis and Futuna',
    alphaCode2: 'WF',
    alphaCode3: 'WLF',
    numericCode: 876,
    lat: -13.3,
    lng: -176.2,
    emoji: '🇼🇫',
  },
  EH: {
    country: 'Western Sahara',
    alphaCode2: 'EH',
    alphaCode3: 'ESH',
    numericCode: 732,
    lat: 24.5,
    lng: -13,
    emoji: '🇪🇭',
  },
  YE: {
    country: 'Yemen',
    alphaCode2: 'YE',
    alphaCode3: 'YEM',
    numericCode: 887,
    lat: 15,
    lng: 48,
    emoji: '🇾🇪',
  },
  ZM: {
    country: 'Zambia',
    alphaCode2: 'ZM',
    alphaCode3: 'ZMB',
    numericCode: 894,
    lat: -15,
    lng: 30,
    emoji: '🇿🇲',
  },
  ZW: {
    country: 'Zimbabwe',
    alphaCode2: 'ZW',
    alphaCode3: 'ZWE',
    numericCode: 716,
    lat: -20,
    lng: 30,
    emoji: '🇿🇼',
  },
  AX: {
    country: 'Åland Islands',
    alphaCode2: 'AX',
    alphaCode3: 'ALA',
    numericCode: 248,
    lat: 60.116667,
    lng: 19.9,
    emoji: '🇦🇽',
  },
  BQ: {
    country: 'Bonaire',
    alphaCode2: 'BQ',
    alphaCode3: 'BES',
    numericCode: 535,
    lat: 12.183333,
    lng: -68.233333,
    emoji: '🇧🇶',
  },
  CW: {
    country: 'Curaçao',
    alphaCode2: 'CW',
    alphaCode3: 'CUW',
    numericCode: 531,
    lat: 12.166667,
    lng: -68.966667,
    emoji: '🇨🇼',
  },
  BL: {
    country: 'Saint Barthélemy',
    alphaCode2: 'BL',
    alphaCode3: 'BLM',
    numericCode: 652,
    lat: 17.897728,
    lng: -62.834244,
    emoji: '🇧🇱',
  },
  MF: {
    country: 'Saint Martin (French part)',
    alphaCode2: 'MF',
    alphaCode3: 'MAF',
    numericCode: 663,
    lat: 18.075278,
    lng: -63.06,
    emoji: '🇲🇫',
  },
  SX: {
    country: 'Sint Maarten (Dutch part)',
    alphaCode2: 'SX',
    alphaCode3: 'SXM',
    numericCode: 534,
    lat: 18.033333,
    lng: -63.05,
    emoji: '🇸🇽',
  },
  XK: {
    country: 'Kosovo',
    alphaCode2: 'XK',
    alphaCode3: 'XKX',
    numericCode: -1,
    lat: 42.583333,
    lng: 21,
    emoji: '🇽🇰',
  },
}
